# -----------------
# 1. project paths
# -----------------

paths:
  data_dir: "dataset/"
  raw_dir: "dataset/raw/"
  processed_dir: "dataset/processed/"
  results_dir: "results/"
  src_dir: "src/"
  NPBOS_dir: "NPBOS/"

# -----------------
# 2. info about nuclei data
# -----------------
nuclei:
  p_min: 60
  p_max: 64
  p_step: 2
  n_min: 86
  n_max: 100
  n_step: 2
  magic_numbers: [2, 8, 20, 28, 50, 82, 126]

# -----------------
# 3. NN model settings
# -----------------
nn:
  input_dim: 4
  output_dim: 3
  nodes_options: [8, 16, 32, 64]
  layers_options: [2, 3, 4]

# -----------------
# 4. training parameters
# -----------------
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 500
  val_ratio: 0.1
  base_seed: 42
  early_stopping_patience: 50
  lr_factor: 0.5
  lr_patience: 20
  beta_min: -0.40
  beta_max: 0.50